stages:
- build
- test
- dockerize

build:
  stage: build
  image: docker.dev.dszn.cz/golang1.10:stretch
  script:
  - mkdir -p /GO/src/github.com/seznam/
  - ln -s $(pwd) /GO/src/github.com/seznam/ProPsy
  - cd /GO/src/github.com/seznam/ProPsy && CGO_ENABLED=0 go build -ldflags='-s -w -extldflags "-static"' main.go
  - mkdir dist
  - cp main dist/propsy
  artifacts:
    paths:
    - dist/propsy
    expire_in: 1 week

buildcurl:
  stage: build
  image: docker.dev.dszn.cz/golang1.10:stretch
  script:
  - go get github.com/fullstorydev/grpcurl
  - go install github.com/fullstorydev/grpcurl/cmd/grpcurl
  - mkdir -p dist
  - cp /GO/bin/grpcurl dist/grpcurl
  artifacts:
    paths:
    - dist/grpcurl
    expire_in: 1 week

testsrc:
  stage: test
  image: docker.dev.dszn.cz/golang1.10:stretch
  script:
  - mkdir -p /GO/src/github.com/seznam/
  - ln -s $(pwd) /GO/src/github.com/seznam/ProPsy
  - cd /GO/src/github.com/seznam/ProPsy && go test -cover ./...

teste2e:
  stage: test
  image: docker.dev.dszn.cz/debian:stretch
  before_script:
  - apt-get update
  - apt-get -y install --no-install-recommends --no-install-suggests adm-kubernetes-hyperkube adm-etcd adm-kubectl git jq
  - git clone https://github.com/envoyproxy/data-plane-api.git proto/data-plane-api
  - cp -rp proto/extras/* proto/data-plane-api/
  - mkdir -p /tmp/log/
  - nohup /www/adm/etcd/bin/etcd --data-dir /tmp/etcd --name etcd-test >/tmp/log/etcd.log 2>&1 &
  - nohup /www/adm/kubernetes/bin/hyperkube apiserver --etcd-servers=http://localhost:2379 >/tmp/log/apiserver.log 2>&1 &
  - /bin/sh -c 'while [ true ]; do curl http://localhost:8080 >/dev/null 2>&1 && exit 0; echo "Not ready yet ... " ; sleep 3 ; done'
  - /bin/sh -c 'for i in deployment/kubernetes/*.yaml; do kubectl apply -f $i ; done'
  - nohup dist/propsy -zone test -configcluster hack/test/kubeconfig.test.yaml:test -endpointcluster hack/test/kubeconfig.test.yaml:1 &
  script:
  - /bin/sh -c 'for i in hack/test/stage1/*.sh; do echo ">>>>>> Running test $i" ; ./$i ; done'
  after_script:
  - echo "Apiserver log --------"
  - cat /tmp/log/apiserver.log
  - echo "ETCD log -------"
  - cat /tmp/log/etcd.log
  - /bin/sh -c 'killall -9 propsy hyperkube etcd || :'

dockerize:
  stage: dockerize
  image: docker.dev.dszn.cz/debian-docker-engine:stretch
  script:
  - docker build --pull -t cid.dev.dszn.cz/admins5/propsy:${CI_PIPELINE_ID} .
  - docker push cid.dev.dszn.cz/admins5/propsy:${CI_PIPELINE_ID}
