/*
This file has been generated.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "gitlab.seznam.net/propsy/pkg/client/clientset/versioned/typed/propsy/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePropsyV1 struct {
	*testing.Fake
}

func (c *FakePropsyV1) ProPsyServices(namespace string) v1.ProPsyServiceInterface {
	return &FakeProPsyServices{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePropsyV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
