/*
This file has been generated.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// ProPsyServiceListerExpansion allows custom methods to be added to
// ProPsyServiceLister.
type ProPsyServiceListerExpansion interface{}

// ProPsyServiceNamespaceListerExpansion allows custom methods to be added to
// ProPsyServiceNamespaceLister.
type ProPsyServiceNamespaceListerExpansion interface{}
