/*
This file has been generated.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	propsyv1 "gitlab.seznam.net/propsy/pkg/apis/propsy/v1"
	versioned "gitlab.seznam.net/propsy/pkg/client/clientset/versioned"
	internalinterfaces "gitlab.seznam.net/propsy/pkg/client/informers/externalversions/internalinterfaces"
	v1 "gitlab.seznam.net/propsy/pkg/client/listers/propsy/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ProPsyServiceInformer provides access to a shared informer and lister for
// ProPsyServices.
type ProPsyServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ProPsyServiceLister
}

type proPsyServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewProPsyServiceInformer constructs a new informer for ProPsyService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewProPsyServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredProPsyServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredProPsyServiceInformer constructs a new informer for ProPsyService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredProPsyServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PropsyV1().ProPsyServices(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PropsyV1().ProPsyServices(namespace).Watch(options)
			},
		},
		&propsyv1.ProPsyService{},
		resyncPeriod,
		indexers,
	)
}

func (f *proPsyServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredProPsyServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *proPsyServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&propsyv1.ProPsyService{}, f.defaultInformer)
}

func (f *proPsyServiceInformer) Lister() v1.ProPsyServiceLister {
	return v1.NewProPsyServiceLister(f.Informer().GetIndexer())
}
