apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: propsyservices.propsy.seznam.cz
spec:
  group: propsy.seznam.cz
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: propsyservices
    singular: propsyservice
    kind: ProPsyService
    shortNames:
    - pps
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ["service", "nodes", "percent", "servicePort", "listen", "timeout"]
          properties:
            listen:
              type: string
            service: 
              type: string
            servicePort:
              type: integer
              minimum: 1
              maximum: 65535
            percent:
              type: integer
              minimum: 0
              maximum: 100
            nodes:
              type: array
              items:
                type: string
            canaryService:
              type: string
            canaryPercent:
              type: integer
              minimum: 0
              maximum: 100
            timeout:
              type: integer
              minimum: 1
              maximum: 600000
            connectTimeout:
              type: integer
              minimum: 1
              maximum: 60000
            maxRequestsPerConnection:
              type: integer
              minimum: 0
            type:
              type: string
              enum:
              - HTTP
              - TCP
            pathPrefix:
              type: string
            prefixRewrite:
              type: string
            tlsCertificateSecret:
              type: string
            healthCheckTimeout:
              type: integer
            healthCheckInterval:
              type: integer
            healthCheckUnhealthyTreshold:
              type: integer
            healthCheckHealthyTreshold:
              type: integer
            healthCheckReuseConnection:
              type: bool
            healthCheckType:
              type: string
              enum:
              - HTTP
              - HTTP2
              - TCP
              - GRPC
            healthCheckHTTPPath:
              type: string
            healthCheckHTTPHost:
              type: string
  additionalPrinterColumns:
  - name: Service
    type: string
    description: Name of the service the endpoints will be stolen from
    JSONPath: .spec.service
  - name: Percent
    type: integer
    description: How much percent of traffic will go into this service in this locality
    JSONPath: .spec.percent
  - name: Timeout
    type: integer
    description: Connect Timeout to upstream endpoints
    JSONPath: .spec.timeout
  - name: Type
    type: string
    description: "Type of the proxied service. Known types: HTTP, TCP (default HTTP)"
    JSONPath: .spec.type
  - name: Path
    type: string
    description: Path of the URL (default /)
    JSONPath: .spec.pathPrefix