apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: propsy
rules:
- apiGroups:
  - propsy.seznam.cz
  resources:
  - propsyservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - secrets
  verbs:
  - list
  - watch
  - get
